import * as flsFunctions from "./modules/functions.js";
import * as sideBar from "./modules/sideBar.js";
import * as navMenu from "./modules/navMenu.js";
import * as langSwitcher from "./modules/langSwitcher.js";
import { setupProductFilters } from './modules/tagFilters.js';
import { enableSubmitWhenAllRequiredFieldsFilled } from './modules/enableSubmit.js';
import { setupContentToggle } from './modules/contentToggle.js';
import { setupCartButtons } from './modules/cartButtons.js';
import { setupTariffSelect } from './modules/tariffSelect.js';
import { initTabs } from './modules/tabs.js';
import { toggleDescription } from './modules/descriptionToggle.js';
import { setupCopyLink } from './modules/copyLink.js';
import { initRatingStars } from './modules/ratingStars.js';
import { autoResizeTextareas } from './modules/autoTextarea.js';
import * as modals from "./modules/modals.js";

setupProductFilters();
enableSubmitWhenAllRequiredFieldsFilled();
setupContentToggle();
setupCartButtons();
setupTariffSelect();
initTabs();
toggleDescription();
setupCopyLink();
initRatingStars();
autoResizeTextareas();